name: Test Pandoc

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Pandoc and TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Create sample Markdown
        run: echo "# Hello Kubernetes" > hello.md

      - name: Convert to PDF
        run: pandoc hello.md -o hello.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: hello-pdf
          path: hello.pdf
